pipeline: 'baseline'
backbone: 'agcrn'
in_horizon: 12
out_horizon: 12
dtype: 'float32'
adj_type: 'None'

backbone_specs:
  in_dim: 1
  out_dim: 1
  rnn_dim: 64
  num_layers: 2
  cheb_k: 2

data_specs:
  dataset: 'pems_08'

learn_specs:
  opt_name: 'adam'
  pt_lr: 0.003
  pt_wd: 0
  batch_size: 64
  train_epoch: 100
  pt_sched_policy: 'None'
  pt_num_epoch_fix_lr: 0
  pt_decay_step: 0
  pt_gamma: 0
  pt_clip_grad: 'None'
  patience: -1
