pipeline: 'baseline'
backbone: 'dcrnn'
in_horizon: 12
out_horizon: 12
dtype: 'float32'
adj_type: 'None'

backbone_specs:
  in_dim: 2
  out_dim: 1
  rnn_dim: 64
  num_layers: 2
  max_diffusion_step: 2
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  use_curriculum_learning: True

data_specs:
  dataset: 'pems_03'

learn_specs:
  opt_name: 'adam'
  pt_lr: 0.01
  pt_eps: 0.001
  pt_wd: 0.0001
  batch_size: 64
  train_epoch: 100
  pt_sched_policy: 'm_step'
  pt_num_epoch_fix_lr: 0
  pt_decay_step: 0
  pt_gamma: 0.1
  pt_milestones: [20, 30, 40, 50]
  pt_clip_grad: 5
  patience: -1

  